import { FormEvent, useEffect, useState } from 'react'; import { content } from './content';
export default function App(){const[menu,setMenu]=useState(false);const[status,setStatus]=useState('');useEffect(()=>{document.title=content.meta.title},[]);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const values=['name','email','message'].map(k=>String(form.get(k)||''));setStatus(values.some(v=>!v)?content.contact.required:!/^\S+@\S+\.\S+$/.test(values[1])?content.contact.invalid:content.contact.success)};return <>
<header><a className="logo" href="#top" aria-label={content.brand.homeLabel}>{content.brand.name}</a><span className="location">{content.brand.location}</span><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu}>{menu?content.navigation.closeLabel:content.navigation.menuLabel}</button><nav className={menu?'open':''}>{content.navigation.items.map(x=><a href={x.href} key={x.href} onClick={()=>setMenu(false)}>{x.label}</a>)}<a className="nav-cta" href="#contact">{content.navigation.cta} ↗</a></nav></header>
<main id="top"><section className="hero"><div className="hero-top"><p>{content.hero.kicker}</p><p className="intro">{content.hero.body}</p></div><h1>{content.hero.titleLead}<br/><em>{content.hero.titleAccent}</em></h1><div className="hero-media"><img src={content.hero.image} alt={content.hero.imageAlt}/><a href="#work" className="round-link">{content.hero.cta}<span>↘</span></a></div><p className="scroll">{content.hero.scroll} ↓</p></section>
<div className="ticker" aria-hidden="true"><div>{[...content.ticker,...content.ticker].map((x,i)=><span key={`${x}-${i}`}>{x} <b>✳</b></span>)}</div></div>
<section className="work wrap" id={content.work.id}><SectionHead number={content.work.number} eyebrow={content.work.eyebrow}/><h2>{content.work.title}</h2><div className="projects">{content.work.projects.map((p,i)=><article className={`project ${p.color}`} key={p.client}><a href="#contact" aria-label={`${content.work.openLabel}: ${p.title}`}><div className="project-image"><img src={p.image} alt={p.alt}/><span>0{i+1} ↗</span></div><div className="project-meta"><div><p>{p.client}</p><h3>{p.title}</h3></div><p>{p.category}<br/>{p.year}</p></div></a></article>)}</div></section>
<section className="studio wrap" id={content.studio.id}><SectionHead number={content.studio.number} eyebrow={content.studio.eyebrow}/><div className="studio-grid"><div><h2>{content.studio.title}</h2><p className="large-copy">{content.studio.body}</p><div className="facts">{content.studio.facts.map(f=><div key={f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div></div><img src={content.studio.image} alt={content.studio.alt}/></div></section>
<section className="services wrap" id={content.services.id}><SectionHead number={content.services.number} eyebrow={content.services.eyebrow}/><h2>{content.services.title}</h2><div className="service-list">{content.services.items.map(s=><article key={s.number}><span>{s.number}</span><h3>{s.title}</h3><p>{s.details}</p><b>↗</b></article>)}</div></section>
<section className="contact" id={content.contact.id}><div><p>{content.contact.eyebrow}</p><h2>{content.contact.title}</h2><p>{content.contact.body}</p><a href={`mailto:${content.contact.email}`}>{content.contact.email} ↗</a></div><form onSubmit={submit} noValidate><label>{content.contact.nameLabel}<input name="name" placeholder={content.contact.namePlaceholder}/></label><label>{content.contact.emailLabel}<input name="email" type="email" placeholder={content.contact.emailPlaceholder}/></label><label>{content.contact.messageLabel}<textarea name="message" placeholder={content.contact.messagePlaceholder}/></label><button>{content.contact.button}</button><p className={status===content.contact.success?'success':''} aria-live="polite">{status}</p></form></section></main>
<footer><a className="logo" href="#top">{content.brand.name}</a><div>{content.footer.socials.map(s=><a href={s.href} key={s.label}>{s.label} ↗</a>)}</div><a href="#top">{content.footer.top}</a><small>{content.footer.copyright}</small></footer></>}
function SectionHead({number,eyebrow}:{number:string;eyebrow:string}){return <div className="section-head"><span>({number})</span><p>{eyebrow}</p><i/></div>}
