import{useEffect,useMemo,useState}from'react';import{content}from'./content';
export default function App(){const[menu,setMenu]=useState(false);const[filter,setFilter]=useState(content.work.all);useEffect(()=>{document.title=content.meta.title},[]);const categories=[content.work.all,...new Set(content.work.projects.map(p=>p.category))];const projects=useMemo(()=>filter===content.work.all?content.work.projects:content.work.projects.filter(p=>p.category===filter),[filter]);return <>
<header><a className="brand" href="#top" aria-label={content.brand.homeLabel}>{content.brand.name}</a><p><i/>{content.brand.availability}</p><button onClick={()=>setMenu(!menu)} aria-expanded={menu}>{content.navigation.menuLabel}<span>{menu?'×':'+'}</span></button><nav className={menu?'open':''}>{content.navigation.items.map(n=><a href={n.href} key={n.href} onClick={()=>setMenu(false)}>{n.label}</a>)}</nav></header>
<main id="top"><section className="hero"><Label text={content.hero.index}/><div className="hero-grid"><h1>{content.hero.title}</h1><div className="portrait"><img src={content.hero.portrait} alt={content.hero.portraitAlt}/><span>AM</span></div><div className="hero-copy"><p>{content.hero.body}</p><a href="#work">{content.hero.cta} ↓</a></div></div><p className="location">{content.hero.location}</p></section>
<section className="work section" id={content.work.id}><Label text={content.work.index}/><div className="title-row"><h2>{content.work.title}</h2><div className="filters" aria-label={content.work.filterLabel}>{categories.map(c=><button className={filter===c?'active':''} aria-pressed={filter===c} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div></div><div className="project-grid">{projects.map((p,i)=><article className={i%3===0?'wide':''} key={p.number}><a href="#contact" aria-label={`${content.work.viewLabel}: ${p.title}`}><div className="image"><img src={p.image} alt={p.alt}/><span>↗</span></div><div className="meta"><span>{p.number}</span><div><h3>{p.title}</h3><p>{p.client}</p></div><p>{p.category}<br/>{p.year}</p></div></a></article>)}</div></section>
<section className="about section" id={content.about.id}><Label text={content.about.index}/><div className="about-grid"><h2>{content.about.title}</h2><div><p className="about-copy">{content.about.body}</p><h3>{content.about.servicesLabel}</h3><ul>{content.about.services.map(s=><li key={s}>{s}<span>↗</span></li>)}</ul></div></div><div className="facts">{content.about.facts.map(f=><div key={f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div></section>
<section className="experience section"><Label text={content.experience.index}/><h2>{content.experience.title}</h2><div>{content.experience.items.map(x=><article key={x.years}><span>{x.years}</span><h3>{x.role}</h3><p>{x.company}</p></article>)}</div></section>
<section className="contact" id={content.contact.id}><Label text={content.contact.index}/><p>{content.contact.eyebrow}</p><h2>{content.contact.title}</h2><a className="email" href={`mailto:${content.contact.email}`}>{content.contact.email}<span>↗</span></a><div className="socials"><span>{content.contact.emailLabel}</span>{content.contact.socials.map(s=><a href={s.href} key={s.label}>{s.label} ↗</a>)}</div></section></main>
<footer><span>{content.footer.copyright}</span><span>{content.footer.note}</span><a href="#top">{content.footer.top}</a></footer></>}
function Label({text}:{text:string}){return <div className="label"><span>{text}</span><i/></div>}
