import{FormEvent,useEffect,useState}from'react';import{content}from'./content';
export default function App(){const[menuOpen,setMenuOpen]=useState(false);const[category,setCategory]=useState(content.menu.categories[0].name);const[reserve,setReserve]=useState(false);const[status,setStatus]=useState('');const[news,setNews]=useState(false);useEffect(()=>{document.title=content.meta.title},[]);const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const email=String(new FormData(e.currentTarget).get('email')||'');setStatus(!email?content.reservation.required:!/^\S+@\S+\.\S+$/.test(email)?content.reservation.invalid:content.reservation.success)};const active=content.menu.categories.find(c=>c.name===category)!;return <>
<header><a className="brand" href="#top" aria-label={content.brand.homeLabel}>{content.brand.monogram}</a><button className="menu-button" aria-expanded={menuOpen} aria-label={content.navigation.menuLabel} onClick={()=>setMenuOpen(!menuOpen)}><i/><i/></button><nav className={menuOpen?'open':''}>{content.navigation.items.map(n=><a href={n.href} key={n.href} onClick={()=>setMenuOpen(false)}>{n.label}</a>)}<button onClick={()=>setReserve(true)}>{content.navigation.cta}</button></nav></header>
<main id="top"><section className="hero"><img src={content.hero.image} alt={content.hero.alt}/><div className="shade"/><p className="eyebrow">{content.hero.eyebrow}</p><div className="hero-title"><h1>{content.hero.title}</h1><p>{content.hero.body}</p><a href="#menu">{content.hero.cta} ↓</a></div><p className="hours">{content.hero.hours}</p></section>
<section className="story" id={content.story.id}><div className="story-copy"><p className="eyebrow">{content.story.eyebrow}</p><h2>{content.story.title}</h2><p>{content.story.body}</p><a href="#visit">{content.story.link} ↗</a></div><div className="story-image"><img src={content.story.image} alt={content.story.alt}/><blockquote>“{content.story.quote}”<span>{content.story.quoteBy}</span></blockquote></div></section>
<section className="menu-section" id={content.menu.id}><div className="menu-heading"><p className="eyebrow">{content.menu.eyebrow}</p><h2>{content.menu.title}</h2><p>{content.menu.note}</p></div><div className="tabs" role="tablist" aria-label={content.menu.tabLabel}>{content.menu.categories.map(c=><button role="tab" aria-selected={category===c.name} className={category===c.name?'active':''} onClick={()=>setCategory(c.name)} key={c.name}>{c.name}</button>)}</div><div className="dishes">{active.items.map(d=><article key={d.name}><div><h3>{d.name}</h3><p>{d.description}</p></div><span>{content.menu.currency}{d.price}</span></article>)}</div></section>
<section className="gallery" aria-label={content.gallery.label}>{content.gallery.images.map((img,i)=><img className={`gallery-${i+1}`} src={img.src} alt={img.alt} key={img.src}/>)}</section>
<section className="visit" id={content.visit.id}><div><p className="eyebrow">{content.visit.eyebrow}</p><h2>{content.visit.title}</h2><address>{content.visit.address.split('\n').map(x=><span key={x}>{x}</span>)}</address><a href={`tel:${content.visit.phone}`}>{content.visit.phone}</a><a href={`mailto:${content.visit.email}`}>{content.visit.email}</a><h3>{content.visit.hoursTitle}</h3>{content.visit.hours.map(h=><p key={h}>{h}</p>)}<button onClick={()=>setReserve(true)}>{content.navigation.cta} ↗</button></div><a className="map" href="#top" aria-label={content.visit.mapLabel}><img src={content.visit.mapImage} alt={content.visit.mapAlt}/><span>⌖</span></a></section>
</main><footer><a className="footer-brand" href="#top">{content.brand.name}</a><form onSubmit={e=>{e.preventDefault();setNews(true)}}><label htmlFor="news">{content.footer.newsletter}</label><div><input id="news" type="email" required placeholder={content.footer.newsletterPlaceholder} aria-label={content.footer.newsletterLabel}/><button>{content.footer.newsletterButton}</button></div><p aria-live="polite">{news?content.footer.newsletterSuccess:''}</p></form><div>{content.footer.socials.map(s=><a href={s.href} key={s.label}>{s.label}</a>)}</div><small>{content.footer.copyright}</small></footer>
{reserve&&<div className="modal" role="dialog" aria-modal="true" aria-labelledby="reserve-title"><button className="close" onClick={()=>setReserve(false)} aria-label={content.reservation.closeLabel}>×</button><p className="eyebrow">{content.reservation.eyebrow}</p><h2 id="reserve-title">{content.reservation.title}</h2><form onSubmit={submit} noValidate><label>{content.reservation.dateLabel}<input name="date" type="date"/></label><label>{content.reservation.timeLabel}<select name="time">{content.reservation.times.map(t=><option key={t}>{t}</option>)}</select></label><label>{content.reservation.guestsLabel}<select name="guests">{content.reservation.guestOptions.map(g=><option key={g}>{g}</option>)}</select></label><label>{content.reservation.emailLabel}<input name="email" type="email" placeholder={content.reservation.emailPlaceholder}/></label><button>{content.reservation.button}</button><p className={status===content.reservation.success?'success':''} aria-live="polite">{status||content.reservation.disclaimer}</p></form></div>}</>}
